// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfhwXKieADzRumdm9I1pKNb3B2zw6EeZg',
    appId: '1:317698837223:web:d8f1e65c8e3e1c5b13b042',
    messagingSenderId: '317698837223',
    projectId: 'flutter-full-news-39a71',
    authDomain: 'flutter-full-news-39a71.firebaseapp.com',
    storageBucket: 'flutter-full-news-39a71.appspot.com',
    measurementId: 'G-5XPP6F4MKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB9YdSmXCXEfA1hVkRn6kDJbcJiLXG6oE',
    appId: '1:317698837223:android:aea1539f0940861313b042',
    messagingSenderId: '317698837223',
    projectId: 'flutter-full-news-39a71',
    storageBucket: 'flutter-full-news-39a71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChR97obp86JhtI8zFM-Crs8FxS1u1TeW0',
    appId: '1:317698837223:ios:f10dde82a72e784b13b042',
    messagingSenderId: '317698837223',
    projectId: 'flutter-full-news-39a71',
    storageBucket: 'flutter-full-news-39a71.appspot.com',
    iosClientId: '317698837223-ohfcdfklbg5km2ukc900mt1pkqo6fmcu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFullFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChR97obp86JhtI8zFM-Crs8FxS1u1TeW0',
    appId: '1:317698837223:ios:f10dde82a72e784b13b042',
    messagingSenderId: '317698837223',
    projectId: 'flutter-full-news-39a71',
    storageBucket: 'flutter-full-news-39a71.appspot.com',
    iosClientId: '317698837223-ohfcdfklbg5km2ukc900mt1pkqo6fmcu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFullFirebaseApp',
  );
}
